repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [typing-extensions]
        args: ["--ignore-missing-imports", "--no-strict-optional", "--disable-error-code=var-annotated", "--disable-error-code=no-untyped-def", "--disable-error-code=return-value", "--disable-error-code=assignment", "--disable-error-code=attr-defined", "--disable-error-code=name-defined", "--disable-error-code=unreachable", "--disable-error-code=no-any-return", "--disable-error-code=arg-type", "--disable-error-code=index", "--disable-error-code=valid-type"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  - repo: local
    hooks:
      - id: pytest-quick
        name: Run quick tests
        entry: pytest
        language: system
        args: [tests/, -x, --tb=short]
        pass_filenames: false

      - id: mypy-src
        name: Type check source code
        entry: mypy
        language: system
        args: [src/, --explicit-package-bases]
        pass_filenames: false

      - id: coverage-check
        name: Test coverage validation
        entry: pytest
        language: system
        args: [--cov=harmonic_analysis, --cov-fail-under=60, --tb=short]
        pass_filenames: false

      - id: package-installable
        name: Verify package installability
        entry: python
        language: system
        args: [-m, pip, install, -e, ., --quiet]
        pass_filenames: false
